In [3]:
import pandas as pd 

df = pd.read_csv("/home/bs_thesis/Desktop/Rushi/BS_thesis/survey dataset of task dataset.csv")

df.head()

,Unnamed: 0,Age group,Gender,Medium of School,Conv_diff,Speak_diff,Write_diff,Read_diff,MT_influence,Lect_diff,...,conv_skill,Read_skill_gap,Write_skill_gap,Speak_skill_gap,Lect_skill_gap,conv_skill_gap,core_Skill_Gap,Gap_Level,LDI_cluster,cluster
0,0,15-19,Male,English medium,2,5,3,2,4,1,...,3,0.8,1.8,3.8,-0.2,0.8,1.4,Medium Gap,2,2
1,1,20-25,Female,English medium,2,3,1,2,3,1,...,3,0.8,-0.2,1.8,-0.2,0.8,0.6,Low Gap,1,1
2,2,20-25,Male,English medium,1,1,1,1,1,1,...,4,-0.2,-0.2,-0.2,-0.2,-0.2,-0.2,Low Gap,1,1
3,3,20-25,Male,English medium,1,4,1,1,3,1,...,4,-0.2,-0.2,2.8,-0.2,-0.2,0.4,Low Gap,1,1
4,4,20-25,Male,English medium,1,4,3,1,1,1,...,4,-0.2,1.8,2.8,-0.2,-0.2,0.8,Low Gap,2,2

In [4]:
X = df.drop(columns=['core_Skill_Gap','Read_skill_gap','Write_skill_gap','conv_skill_gap','Lect_skill_gap','Speak_skill_gap','Read_skill','conv_skill','Write_skill','Speak_skill','Lect_skill','Read_diff','Speak_diff','Write_diff','Lect_diff','Conv_diff','Gap_Level','LDI_cluster','cluster','Learning_difficulty_index','LDI_Level'])  # remove useless columns
y = df['core_Skill_Gap']

In [6]:
X = pd.get_dummies(X, drop_first=True)

In [ ]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train, y_test = train_test_split(X, y,test_size= 0.2,random_state= 42)

In [ ]:
from sklearn.linear_model import Lasso

model = Lasso(alpha=0.01)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [12]:
y_pred = model.predict(X_test)

In [13]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error


mse = mean_squared_error(y_test, y_pred)
rmse = mse ** 0.5
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)


print("MSE:",mse)
print("RMSE:", rmse)
print("MAE:", mae)
print("R_Square", r2)

MSE: 0.23052191050972143
RMSE: 0.48012697332030974
MAE: 0.3664026322188316
R_Square 0.7168136808040045

In [14]:
coefficients = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model.coef_
})

In [18]:
coefficients.sort_values(by= "Coefficient",ascending=False)

                             Feature  Coefficient
1                       MT_influence     0.333487
3                          Movie_sub     0.226495
5                        Switch_diff     0.110309
6                         work_india     0.054580
14                       Gender_Male     0.052114
9                        Friend_diff     0.045333
7                        Work_abroad     0.036243
4                      Learning_feel     0.017493
0                         Unnamed: 0     0.000197
12                Age group_Above 25    -0.000000
8                        Study_other    -0.000000
11                   Age group_20-25     0.000000
10                   Age group_15-19    -0.000000
15  Medium of School _English medium    -0.000000
13                Age group_under 10    -0.000000
16   Medium of School _Telugu medium     0.000000
2                        Movie_Nosub    -0.004644