In [16]:
import pandas as pd

df = pd.read_csv("/home/bs_thesis/Desktop/Rushi/BS_thesis/Survey on English Languages Diffculties in Telugu States.csv")

df = df.drop("Timestamp", axis=1)

df.head()

,Age group,Gender,Medium of School,How difficult is it for you to understanding English conversation?\nఆంగ్ల సంభాషణను అర్థం చేసుకోవడం మీకు ఎంత కష్టం?,"How difficult do you find it to speak English confidently while discussing passages or articles?\nప్యాసేజ్‌లు లేదా వ్యాసాల గురించి మాట్లాడేటప్పుడు, ఆత్మవిశ్వాసంతో ఇంగ్లీష్ మాట్లాడటం మీకు ఎంత కష్టం?",How difficult is it for you to write sentences in English?\nమీకు ఆంగ్లంలో వాక్యాలు రాయడం ఎంత కష్టం?,How difficult is it for you to read and understand English passages or articles?\nఇంగ్లీష్ పేరాగ్రాఫ్‌లు లేదా వ్యాసాలను చదివి అర్థం చేసుకోవడం మీకు ఎంత కష్టం?,How difficult is it for you to use English due to the influence of your mother tongue (Telugu)?\nమీ మాతృభాష (తెలుగు) ప్రభావం వల్ల మీకు ఇంగ్లీష్ ఉపయోగించడం ఎంత కష్టంగా ఉంటుంది?,How difficult is it for you to understand lectures in English?\nఇంగ్లీషులో ఉపన్యాసాలను అర్థం చేసుకోవడం మీకు ఎంత కష్టం?,How difficult is it for you to watch English movies without subtitles?\nసబ్‌టైటిల్స్ లేకుండా ఇంగ్లీష్ సినిమాలు చూడటం మీకు ఎంత కష్టం?,"How difficult is it for you to watch English movies even with subtitles?\nసబ్‌టైటిల్స్‌తో చూసినప్పటికీ, మీకు ఇంగ్లీష్ సినిమాలు చూడటం ఎంత కష్టంగా ఉంటుంది?",How do you feel while learning English?\nఇంగ్లీష్ నేర్చుకునేటప్పుడు మీకు ఎలా అనిపిస్తుంది?,"As a Telugu medium student, how difficult was it for you to switch to an English-Medium Curriculum in higher studies?\nతెలుగు మాధ్యమంలో చదివిన విద్యార్థిగా, ఉన్నత విద్యలో ఆంగ్ల మాధ్యమ పాఠ్య ప్రణాళికకు మారడం మీకు ఎంత కష్టంగా అనిపించింది?",How difficult do you find it to work in other Indian states due to language differences?\nభాషా భేదాల కారణంగా ఇతర భారతీయ రాష్ట్రాలలో పని చేయడం మీకు ఎంత కష్టంగా అనిపిస్తుంది?,How difficult do you find it to work in other countries due to language differences?\nభాషా భేదాల కారణంగా ఇతర దేశాలలో పనిచేయడం మీకు ఎంత కష్టంగా అనిపిస్తుంది?,How difficult do you find it to study in other Indian states or other countries due to language differences?\nభాషా భేదాల కారణంగా ఇతర భారతీయ రాష్ట్రాలలో లేదా ఇతర దేశాలలో చదువుకోవడం మీకు ఎంత కష్టంగా అనిపిస్తుంది?,How difficult do you find it to make friends who have different native languages?\nవేర్వేరు మాతృభాషలు ఉన్నవారితో స్నేహం చేయడం మీకు ఎంత కష్టంగా అనిపిస్తుంది?
0,15-19,Male,English medium,2,5,3,2,4,1,2,1,2,1,4,4,4,3
1,20-25,Female,English medium,2,3,1,2,3,1,3,1,1,1,2,3,2,2
2,20-25,Male,English medium,1,1,1,1,1,1,1,1,5,5,4,4,4,5
3,20-25,Male,English medium,1,4,1,1,3,1,2,1,2,1,4,4,4,3
4,20-25,Male,English medium,1,4,3,1,1,1,2,1,2,1,4,4,3,3

In [17]:
df = df.rename(columns={
"How difficult is it for you to understanding English conversation?\nఆంగ్ల సంభాషణను అర్థం చేసుకోవడం మీకు ఎంత కష్టం?":"Conv_diff",

"How difficult do you find it to speak English confidently while discussing passages or articles?\nప్యాసేజ్‌లు లేదా వ్యాసాల గురించి మాట్లాడేటప్పుడు, ఆత్మవిశ్వాసంతో ఇంగ్లీష్ మాట్లాడటం మీకు ఎంత కష్టం?":"Speak_diff",

"How difficult is it for you to write sentences in English?\nమీకు ఆంగ్లంలో వాక్యాలు రాయడం ఎంత కష్టం?": "Write_diff",

"How difficult is it for you to read and understand English passages or articles?\nఇంగ్లీష్ పేరాగ్రాఫ్‌లు లేదా వ్యాసాలను చదివి అర్థం చేసుకోవడం మీకు ఎంత కష్టం?":"Read_diff",

"How difficult is it for you to use English due to the influence of your mother tongue (Telugu)?\nమీ మాతృభాష (తెలుగు) ప్రభావం వల్ల మీకు ఇంగ్లీష్ ఉపయోగించడం ఎంత కష్టంగా ఉంటుంది?": "MT_influence",

"How difficult is it for you to understand lectures in English?\nఇంగ్లీషులో ఉపన్యాసాలను అర్థం చేసుకోవడం మీకు ఎంత కష్టం?": "Lect_diff",

"How difficult is it for you to watch English movies without subtitles?\nసబ్‌టైటిల్స్ లేకుండా ఇంగ్లీష్ సినిమాలు చూడటం మీకు ఎంత కష్టం?": "Movie_Nosub",

"How difficult is it for you to watch English movies even with subtitles?\nసబ్‌టైటిల్స్‌తో చూసినప్పటికీ, మీకు ఇంగ్లీష్ సినిమాలు చూడటం ఎంత కష్టంగా ఉంటుంది?": "Movie_sub",

"How do you feel while learning English?\nఇంగ్లీష్ నేర్చుకునేటప్పుడు మీకు ఎలా అనిపిస్తుంది?":"Learning_feel",

"As a Telugu medium student, how difficult was it for you to switch to an English-Medium Curriculum in higher studies?\nతెలుగు మాధ్యమంలో చదివిన విద్యార్థిగా, ఉన్నత విద్యలో ఆంగ్ల మాధ్యమ పాఠ్య ప్రణాళికకు మారడం మీకు ఎంత కష్టంగా అనిపించింది?":"Switch_diff",

"How difficult do you find it to work in other Indian states due to language differences?\nభాషా భేదాల కారణంగా ఇతర భారతీయ రాష్ట్రాలలో పని చేయడం మీకు ఎంత కష్టంగా అనిపిస్తుంది?":"work_india",

"How difficult do you find it to work in other countries due to language differences?\nభాషా భేదాల కారణంగా ఇతర దేశాలలో పనిచేయడం మీకు ఎంత కష్టంగా అనిపిస్తుంది?":"Work_abroad",

"How difficult do you find it to study in other Indian states or other countries due to language differences?\nభాషా భేదాల కారణంగా ఇతర భారతీయ రాష్ట్రాలలో లేదా ఇతర దేశాలలో చదువుకోవడం మీకు ఎంత కష్టంగా అనిపిస్తుంది?":"Study_other",

"How difficult do you find it to make friends who have different native languages?\nవేర్వేరు మాతృభాషలు ఉన్నవారితో స్నేహం చేయడం మీకు ఎంత కష్టంగా అనిపిస్తుంది?":"Friend_diff"})

In [18]:
df["Learning_Difficulty_Index"]= df[
    [
    "Read_diff", 
    "Write_diff",
    "Conv_diff",
    "Lect_diff",
    "Speak_diff"
    ]
].mean(axis=1)

In [19]:
X = df.drop(columns=['Learning_Difficulty_Index','Read_diff','Speak_diff','Conv_diff','Lect_diff','Write_diff'])  # remove useless columns
y = df['Learning_Difficulty_Index']

In [20]:
X = pd.get_dummies(X, drop_first=True)

In [21]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train, y_test = train_test_split(X, y,test_size= 0.2,random_state= 42 )

In [22]:
from sklearn.linear_model import Ridge


model_ridge = Ridge(alpha= 1.0)
model_ridge.fit(X_train, y_train)


y_pred = model_ridge.predict(X_test)

In [23]:
from sklearn.metrics import r2_score, mean_squared_error,mean_absolute_error



mse = mean_squared_error(y_test, y_pred)
rsme = mse **0.5
mae = mean_absolute_error(y_test, y_pred)
r_square = r2_score(y_test, y_pred)

print("mse :",mse)
print("rsme:",rsme)
print("mae:" ,mae)
print("r_square:",r_square)

mse : 0.2341300709342317
rsme: 0.483869890501808
mae: 0.37300673562905357
r_square: 0.7123812098626245

In [24]:
coefficients_Ridge = pd.DataFrame({
    'Feature': X.columns,
    'coefficient_ridge': model_ridge.coef_
})

In [25]:
coefficients_Ridge.sort_values(by= "coefficient_ridge",ascending=False)

                             Feature  coefficient_ridge
0                       MT_influence           0.340949
2                          Movie_sub           0.245212
13                       Gender_Male           0.107970
4                        Switch_diff           0.106282
5                         work_india           0.061696
8                        Friend_diff           0.052524
6                        Work_abroad           0.043382
15   Medium of School _Telugu medium           0.041583
3                      Learning_feel           0.024512
14  Medium of School _English medium          -0.008732
7                        Study_other          -0.015005
1                        Movie_Nosub          -0.032110
9                    Age group_15-19          -0.064584
10                   Age group_20-25          -0.066975
12                Age group_under 10          -0.071506
11                Age group_Above 25          -0.103067