In [2]:
import pandas as pd

df = pd.read_csv("/home/bs_thesis/Desktop/Rushi/BS_thesis/survey dataset of task dataset.csv")


df.head()

,Unnamed: 0,Age group,Gender,Medium of School,Conv_diff,Speak_diff,Write_diff,Read_diff,MT_influence,Lect_diff,...,conv_skill,Read_skill_gap,Write_skill_gap,Speak_skill_gap,Lect_skill_gap,conv_skill_gap,core_Skill_Gap,Gap_Level,LDI_cluster,cluster
0,0,15-19,Male,English medium,2,5,3,2,4,1,...,3,0.8,1.8,3.8,-0.2,0.8,1.4,Medium Gap,2,2
1,1,20-25,Female,English medium,2,3,1,2,3,1,...,3,0.8,-0.2,1.8,-0.2,0.8,0.6,Low Gap,1,1
2,2,20-25,Male,English medium,1,1,1,1,1,1,...,4,-0.2,-0.2,-0.2,-0.2,-0.2,-0.2,Low Gap,1,1
3,3,20-25,Male,English medium,1,4,1,1,3,1,...,4,-0.2,-0.2,2.8,-0.2,-0.2,0.4,Low Gap,1,1
4,4,20-25,Male,English medium,1,4,3,1,1,1,...,4,-0.2,1.8,2.8,-0.2,-0.2,0.8,Low Gap,2,2

In [3]:
X = df.drop(columns=['core_Skill_Gap','Read_skill_gap','Write_skill_gap','conv_skill_gap','Lect_skill_gap','Speak_skill_gap','Read_skill','conv_skill','Write_skill','Speak_skill','Lect_skill','Read_diff','Speak_diff','Write_diff','Lect_diff','Conv_diff','Gap_Level','LDI_cluster','cluster','Learning_difficulty_index','LDI_Level'])  # remove useless columns
y = df['core_Skill_Gap']

In [4]:
X = pd.get_dummies(X, drop_first=True)

In [5]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train, y_test = train_test_split(X, y,test_size= 0.2,random_state= 42)

In [6]:
from sklearn.linear_model import Ridge


model_ridge = Ridge(alpha= 1.0)
model_ridge.fit(X_train, y_train)


y_pred = model_ridge.predict(X_test)

In [7]:
from sklearn.metrics import r2_score, mean_squared_error,mean_absolute_error



mse = mean_squared_error(y_test, y_pred)
rsme = mse **0.5
mae = mean_absolute_error(y_test, y_pred)
r_square = r2_score(y_test, y_pred)

print("mse :",mse)
print("rsme:",rsme)
print("mae:" ,mae)
print("r_square:",r_square)

mse : 0.23333511612171784
rsme: 0.4830477368974187
mae: 0.3698337356831701
r_square: 0.7133577778894347

In [8]:
coefficients_Ridge = pd.DataFrame({
    'Feature': X.columns,
    'coefficient_ridge': model_ridge.coef_
})

In [9]:
coefficients_Ridge.sort_values(by= "coefficient_ridge",ascending=False)

                             Feature  coefficient_ridge
1                       MT_influence           0.343730
3                          Movie_sub           0.240390
5                        Switch_diff           0.107849
14                       Gender_Male           0.103179
6                         work_india           0.059266
16   Medium of School _Telugu medium           0.058354
9                        Friend_diff           0.052237
7                        Work_abroad           0.046672
4                      Learning_feel           0.021916
15  Medium of School _English medium           0.003255
0                         Unnamed: 0           0.000165
8                        Study_other          -0.013890
2                        Movie_Nosub          -0.031164
10                   Age group_15-19          -0.060734
11                   Age group_20-25          -0.061973
13                Age group_under 10          -0.082519
12                Age group_Above 25          -0.097344